---
# tasks file for docker-registry.

- name: Log into DockerHub
  docker_login:
    username: mekki209
    password: 34f8e81c-320b-422d-b47a-833a174149ac

- name: Tag and push to docker hub
  docker_image:
    name: myapp:latest
    repository: mekki209/myapp
    tag: end
    push: yes
